/**
 * crypto.js — Zero-knowledge AES-GCM encryption utilities
 *
 * Key is generated by the sender, exported as base64url, and embedded in the
 * URL hash (e.g. /#key=...) so the signaling server never sees it.
 *
 * Each chunk is encrypted with a unique 12-byte IV derived from:
 *   iv = sessionNonce[0..7] || chunkIndex[0..3]
 * The 8-byte nonce is randomly generated per session and shared in the metadata
 * frame. The 4-byte chunk index makes it deterministic and resumable.
 */

const ALGO = { name: "AES-GCM", length: 256 };

// ─── Key generation & import ──────────────────────────────────────────────────

/** Generate a new AES-GCM-256 key. */
export async function generateKey() {
  return crypto.subtle.generateKey(ALGO, true, ["encrypt", "decrypt"]);
}

/** Export a CryptoKey to a base64url string for embedding in the URL hash. */
export async function exportKeyToBase64(key) {
  const raw = await crypto.subtle.exportKey("raw", key);
  return bufferToBase64url(raw);
}

/** Import a base64url string back into a CryptoKey. */
export async function importKeyFromBase64(b64) {
  const raw = base64urlToBuffer(b64);
  return crypto.subtle.importKey("raw", raw, ALGO, false, ["encrypt", "decrypt"]);
}

// ─── IV derivation ────────────────────────────────────────────────────────────

/** Generate a random 8-byte session nonce (sent once in the metadata frame). */
export function generateNonce() {
  return crypto.getRandomValues(new Uint8Array(8));
}

/**
 * Derive a unique 12-byte IV for each chunk.
 * iv = nonce[8] || chunkIndex[4]  (big-endian)
 */
export function makeIV(nonce, chunkIndex) {
  const iv = new Uint8Array(12);
  iv.set(nonce, 0);
  const view = new DataView(iv.buffer);
  view.setUint32(8, chunkIndex, false); // big-endian
  return iv;
}

// ─── Encrypt / Decrypt ────────────────────────────────────────────────────────

/**
 * Encrypt a plaintext ArrayBuffer.
 * Returns the ciphertext ArrayBuffer (includes GCM auth tag).
 */
export async function encryptChunk(key, iv, data) {
  return crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, data);
}

/**
 * Decrypt a ciphertext ArrayBuffer.
 * Throws if authentication fails (tampered or wrong key).
 */
export async function decryptChunk(key, iv, data) {
  return crypto.subtle.decrypt({ name: "AES-GCM", iv }, key, data);
}

// ─── Binary frame encoding / decoding ─────────────────────────────────────────

/**
 * FRAME FORMAT (all fields big-endian):
 *   [0..3]  chunkIndex  : uint32
 *   [4..7]  totalChunks : uint32
 *   [8..19] iv          : 12 bytes
 *   [20..]  payload     : encrypted data
 *
 * HEADER_SIZE = 20 bytes
 */
export const HEADER_SIZE = 20;

/** Encode a chunk into the wire frame. */
export function encodeFrame(chunkIndex, totalChunks, iv, encryptedPayload) {
  const frame = new Uint8Array(HEADER_SIZE + encryptedPayload.byteLength);
  const view  = new DataView(frame.buffer);
  view.setUint32(0, chunkIndex,  false);
  view.setUint32(4, totalChunks, false);
  frame.set(iv, 8);
  frame.set(new Uint8Array(encryptedPayload), HEADER_SIZE);
  return frame.buffer;
}

/** Decode a wire frame back into its components. */
export function decodeFrame(buffer) {
  const view       = new DataView(buffer);
  const chunkIndex  = view.getUint32(0, false);
  const totalChunks = view.getUint32(4, false);
  const iv          = new Uint8Array(buffer.slice(8, 20));
  const payload     = buffer.slice(HEADER_SIZE);
  return { chunkIndex, totalChunks, iv, payload };
}

// ─── Integrity hashing ────────────────────────────────────────────────────────

/**
 * SHA-256 hash of an ArrayBuffer.
 * Returns lowercase hex string.
 */
export async function hashBuffer(buf) {
  const digest = await crypto.subtle.digest("SHA-256", buf);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// ─── Base64url helpers ────────────────────────────────────────────────────────

export function bufferToBase64url(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary  = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
}

export function base64urlToBuffer(b64) {
  const padded = b64.replace(/-/g, "+").replace(/_/g, "/");
  const pad    = (4 - (padded.length % 4)) % 4;
  const raw    = atob(padded + "=".repeat(pad));
  const buf    = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) buf[i] = raw.charCodeAt(i);
  return buf.buffer;
}

/** Export nonce as base64url for embedding in metadata JSON. */
export function nonceToBase64(nonce) {
  return bufferToBase64url(nonce.buffer);
}

/** Import nonce from base64url string back to Uint8Array[8]. */
export function base64ToNonce(b64) {
  return new Uint8Array(base64urlToBuffer(b64));
}
